const palavras = [
  {palavra: 'Amora', tipo: 'Fruta'},
  {palavra: 'Ameixa', tipo: 'Fruta'},
  {palavra: 'Abaxaxi', tipo: 'Fruta'},
  {palavra: 'Pessego', tipo: 'Fruta'},
  {palavra: 'Jaca', tipo: 'Fruta'},
  {palavra: 'Manga', tipo: 'Fruta'},
  {palavra: 'Acerola', tipo: 'Fruta'},
  {palavra: 'Morango', tipo: 'Fruta'},
  {palavra: 'Caju', tipo: 'Fruta'},
  {palavra: 'Cajamanga', tipo: 'Fruta'},
  {palavra: 'Faca', tipo: 'Objeto'},
  {palavra: 'Espada', tipo: 'Objeto'},
  {palavra: 'Caneta', tipo: 'Objeto'},
  {palavra: 'Caneca', tipo: 'Objeto'},
  {palavra: 'Copo', tipo: 'Objeto'},
  {palavra: 'Garfo', tipo: 'Objeto'},
  {palavra: 'Colher', tipo: 'Objeto'},
  {palavra: 'Armario', tipo: 'Objeto'},
  {palavra: 'Lixeiro', tipo: 'Objeto'},
  {palavra: 'Prato', tipo: 'Objeto'},
  {palavra: 'Tomada', tipo: 'Objeto'},
  {palavra: 'Lampada', tipo: 'Objeto'},
  {palavra: 'Carregador', tipo: 'Objeto'},
  {palavra: 'Sacola', tipo: 'Objeto'},
  {palavra: 'Bolsa', tipo: 'Objeto'},
  {palavra: 'Camelo', tipo: 'Animal'},
  {palavra: 'Passaro', tipo: 'Animal'},
  {palavra: 'Galinha', tipo: 'Animal'},
  {palavra: 'Peixo', tipo: 'Animal'},
  {palavra: 'Vaca', tipo: 'Animal'},
  {palavra: 'Boi', tipo: 'Animal'},
  {palavra: 'Cachorro', tipo: 'Animal'},
  {palavra: 'Tartaruga', tipo: 'Animal'},
  {palavra: 'Formiga', tipo: 'Animal'},
  {palavra: 'Tubarao', tipo: 'Animal'},
  {palavra: 'Gato', tipo: 'Animal'},
  {palavra: 'Sapo', tipo: 'Animal'},
  {palavra: 'Jacare', tipo: 'Animal'},
  {palavra: 'Macaco', tipo: 'Animal'}
]
function sorteio() {
    const indiceSorteado = Math.floor(Math.random() * palavras.length)
    return palavras[indiceSorteado]
}